In [2]:
import numpy as np
import sys

In [15]:
a = np.array([1, 2, 3], dtype = 'int32')
print(a) 

[1 2 3]


In [5]:
b = np.array([[9, 8, 7], [6, 5, 4]])
print(b)

[[9 8 7]
 [6 5 4]]


In [8]:
a.ndim
b.ndim

2

In [9]:
a.shape

(3,)

In [10]:
b.shape

(2, 3)

In [13]:
# Get type 
a.dtype

dtype('int16')

In [16]:
# Get size 
a.itemsize

4

In [18]:
a.nbytes

12

In [19]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [21]:
a[1, -2]

13

In [22]:
# Get a specific row 
a[0, :] 

array([1, 2, 3, 4, 5, 6, 7])

In [23]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [24]:
# Getting a little more fancy
a[0, 1:6:2]

array([2, 4, 6])

In [26]:
a[1, 5] = 20
print(a)

a[:, 2] = 5 
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [28]:
b = np.array([[[1, 2], [3,4]], [[5, 6], [7, 8]]])

In [29]:
b[0, 1, 1]

4

In [33]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.ones((4, 2, 2), dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [36]:
np.full((2, 2), 99)

array([[99, 99],
       [99, 99]])

In [37]:
np.full_like(a.shape, 4)

array([4, 4])

In [38]:
np.random.rand(4, 2)

array([[0.18330508, 0.42155769],
       [0.02964328, 0.57886297],
       [0.41933154, 0.1292316 ],
       [0.38870912, 0.7681535 ]])

In [39]:
np.random.randint(7, size = (3, 3))

array([[0, 3, 4],
       [6, 4, 5],
       [2, 0, 3]])

In [40]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [45]:
output = np.ones((5, 5))
print(output)

z = np.zeros((3, 3))
z[1, 1] = 9

output[1:4, 1:4] = z 
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [47]:
a = np.array([1, 2, 3])
b = a.copy() 
b[0] = 100
print(a)

[1 2 3]


In [48]:
a = np.array([1, 2, 3, 4])
a + 2

array([3, 4, 5, 6])

In [49]:
a - 2

array([-1,  0,  1,  2])

In [50]:
a * 2

array([2, 4, 6, 8])

In [51]:
a / 2

array([0.5, 1. , 1.5, 2. ])