In [12]:
import random 


In [10]:
def get_choice():
    player_choice = input("Enter a choice (rock, paper, scissor: ") 
    options = ["rock", "paper", "scissor"]
    computer_choice = random.choice(options)
    choices = {"player": player_choice, "computer" : computer_choice}
    return choices

In [3]:
def greeting(): 
        return "Hi"

In [13]:
response = greeting()
print(response)

choices = get_choice() 
print(choices)

Hi


Enter a choice (rock, paper, scissor:  rock


{'player': 'rock', 'computer': 'paper'}


In [14]:
def check_win(player, computer): 
    print("You chose " + player + ", computer chose " + computer)
    if player == computer: 
        return "It is a tie"
    elif player == "rock": 
        if computer == "scissors": 
            return "Rock smashes scissors! You win!" 
        else: 
            return "Paper covers rock! You lose" 
    elif player == "paper": 
        if computer == "rock": 
            return "Paper covers rock! You win!" 
        else: 
            return "Scissors cuts paper! You lose"
    elif player == "scissors": 
        if computer == "paper": 
            return "Scissors cuts paper! You win!" 
        else: 
            return "Rock smashes scissors! You lose"

In [18]:
choices = get_choice()
result = check_win(choices["player"], choices["computer"])
print(result)

Enter a choice (rock, paper, scissor:  rock


You chose rock, computer chose scissor
Paper covers rock! You lose


In [21]:
name = "Beau" 
print(type(name) == str); print(isinstance(name, str)) # for string class

True
True


In [24]:
age = 2
print(isinstance(age, int)); print(isinstance(age, float))
age = float(2); age = int("20") 
number = "20"; age = int(number)
print(isinstance(age, int))

True
False
True


In [25]:
print("Scamp" + " is a good dog")

Scamp is a good dog


In [26]:
age = 8 
age += 8
print(age)

16


In [34]:
name = "Beau"
print("beau person".title())
print("beau".upper())
print(len(name)) 
print("au" in name)
name_1 = "Be\"au\""
print(name_1)

Beau Person
BEAU
4
True
Be"au"


In [38]:
print(name[1:3])

ea


In [40]:
done = True

if done: 
    print("yes") 
else: 
    print("no")

yes


In [42]:
ingredient_purchased = True
meal_cooked = True
ready_to_serve = all([ingredient_purchased, meal_cooked])
print(ready_to_serve)

True


In [45]:
from enum import Enum

In [52]:
# creating the constant in Python
class State(Enum): 
    INACTIVE = 0
    ACTIVE = 1

print(State.ACTIVE.value)
print(State['ACTIVE'])
print(list(State))

1
State.ACTIVE
[<State.INACTIVE: 0>, <State.ACTIVE: 1>]


In [55]:
print("What is your age? ")
age =input() 
print("your age is " + age)

What is your age? 


 1


your age is 1


In [58]:
condition = True 

if condition == True: 
    print("The condition was true")
else: 
    pritn("The condition was false")
print("outside if")

The condition was true
outside if


In [72]:
dogs = ["Rogers", "Syd", 1, True, "Quincy", 7]
print("Rogers" in dogs)

dogs[2] = "Beau"
print(dogs[-2])
print(dogs[2:4])
dogs.append("Judah")
dogs.extend(["Judah", 5])
dogs += ["Judah", 5]
dogs.remove("Syd")
print(dogs.pop())
print(len(dogs)) 

True
Quincy
['Beau', True]
5
9


In [81]:
items = ["Rogers", "Syd", "Quincy"]
items[1:1] = ["Test 1", "Test 2"]

items.sort(key=str.lower)
print(items)

itemscopy = items[:]
print(itemscopy)

sorted(items, key = str.lower)

['Quincy', 'Rogers', 'Syd', 'Test 1', 'Test 2']
['Quincy', 'Rogers', 'Syd', 'Test 1', 'Test 2']


['Quincy', 'Rogers', 'Syd', 'Test 1', 'Test 2']

In [90]:
# tuples 
names = ("Roger", "Syd") 
names[-1]
len(names)

print("Rogers" in names)
print(sorted(names))
newTuple = names + ("Henry", "Larry")

False
['Roger', 'Syd']


In [106]:
# Dictionaries
dog = {"name": "Roger", "age": 8, "color": "green"}
dog["name"] = "Syd"
print(dog["name"])
print(dog.get("name"))
print(dog.get("color", "brown"))
print(dog.pop("name"))
print(dog.popitem())
print(dog)
print("color" in dog)
print(list(dog.keys()))
print(len(dog))
dog["favorite food"] = "Meat"
del dog['color']

Syd
Syd
green
Syd
('color', 'green')
{'age': 8}
False
['age']
1


KeyError: 'color'

In [112]:
# Sets 
set1 = {"Roger", "Syd"}
set2 = {"Roger"}

intersect = set1 & set2
print(intersect)

mod = set1 | set2 
print(mod)

subtract = set1 - set2 
print(subtract)

print(list(set1))

{'Roger'}
{'Roger', 'Syd'}
{'Syd'}
['Roger', 'Syd']


In [117]:
def change(value): 
    value["name"] = 2

val = {"name": "beau"}
change(val) 
print(val)

{'name': 2}


In [115]:
def hello(name = "my friend"): 
    print("hello " + name)

hello("Bean")
hello("Quincy")
hello()

hello Bean
hello Quincy
hello my friend


In [118]:
condition = True 

while condition == True: 
    print("The condition is true")
    condition = False

The condition is true


In [119]:
items = [1, 2, 3, 4]
for item in items: 
    print(item)

1
2
3
4


In [120]:
for item in range(15): 
    print(item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [122]:
for index, item in enumerate(items): 
    if item == 2: 
        continue
    print(index, item)

0 1
2 3
3 4


In [130]:
# Classes
class Animal: 
    def walk(self): 
        print("Walking") 
        
class Dog(Animal): 
    def __init__(self, name, age): 
        self.name = name 
        self.age = age 

    def bark(self): 
        print("woof")


        
roger = Dog("Roger", 8)
roger.bark()
print(roger.name, roger.age)
roger.walk()

woof
Roger 8
Walking


In [131]:
import math

In [132]:
print(math.sqrt(4))

2.0


In [133]:
import sys

In [134]:
print(sys.argv)

['/opt/anaconda3/lib/python3.12/site-packages/ipykernel_launcher.py', '-f', '/Users/henrytran/Library/Jupyter/runtime/kernel-20de6f7a-dbed-4a7b-86da-2570de4a9361.json']


In [135]:
import argparse

In [137]:
parser = argparse.ArgumentParser (
    description = "This program prints the name of my dog"
)

In [138]:
parser.add_argument('-c', '--color', metavar = 'color', required = True, help = 'the color to search for')

_StoreAction(option_strings=['-c', '--color'], dest='color', nargs=None, const=None, default=None, type=None, choices=None, required=True, help='the color to search for', metavar='color')

In [139]:
args = parser.parse_args()
print(args.color)

usage: ipykernel_launcher.py [-h] -c color
ipykernel_launcher.py: error: the following arguments are required: -c/--color


SystemExit: 2

/opt/anaconda3/lib/python3.12/site-packages/IPython/core/interactiveshell.py:3585: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [140]:
# Lambda functions 

lambda num : num * 2

multiply = lambda a, b: a * b

print(multiply(2, 4))

8


In [146]:
#map, filter, reduce

numbers = [1, 2, 3]

# def double(a): 
#     return a * 2

# result = map(double, numbers)

result = map(lambda a : a * 2, numbers)
print(list(result))

[2, 4, 6]


In [148]:
numbers = [1, 2, 3] 

def isEven(n): 
    return n % 2 == 0

# result = filter(isEven, numbers)
result = filter(lambda n : n % 2 == 0, numbers)
print(list(result))

[2]


In [150]:
from functools import reduce

In [151]:
expenses = [
    ('Dinner', 80), 
    ('Car repair', 120) 
]

# sum = 0
# for expense in expenses: 
#     sum += expense[1]

sum = reduce(lambda a, b: a[1] + b[1], expenses)
print(sum)

200


In [152]:
# Recursion 
def factorial(n): 
    if n == 1: return 1 
    return n * factorial(n - 1)

In [154]:
# Decorators 

def logtime(func): 
    def wrapper(): 
        print("before")
        val = func() 
        print("after") 
    return wrapper
    
@logtime
def hello(): 
    print("Hello")

hello()

before
Hello
after


In [155]:
"""
    This is a good example
"""

class Dog: 
    def __init__(self, name, age): 
        self.name = name 
        self.age = age 

    def bark(self): 
        print("Woof")

print(help(Dog))

Help on class Dog in module __main__:

class Dog(builtins.object)
 |  Dog(name, age)
 |
 |  Methods defined here:
 |
 |  __init__(self, name, age)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  bark(self)
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  __dict__
 |      dictionary for instance variables
 |
 |  __weakref__
 |      list of weak references to the object

None


In [157]:
# Annotations 

def increment(n: int) -> int: 
    return n + 1

In [160]:
# Exceptions

try: 
    result = 2 / 0
except ZeroDivisionError: 
    print('Cannot divide by zero') 
finally: 
    result = 1

Cannot divide by zero


In [162]:
try: 
    raise Exception('an error!')
except Exception as error: 
    print(error)

an error!


In [163]:
class DogNotFoundException(Exception): 
    pass

try: 
    raise DogNotFoundException()
except DogNotFoundException: 
    print("Dog not found")

Dog not found


In [165]:
# filename = '/Users/flavio/text.txt' 
# with open(filename, 'r') as file: 
#     content = file.read() 
#     print(content)

In [166]:
# List compression 

numbers = [1, 2, 3, 4, 5]
numbers_power_2 = [n**2 for n in numbers] 

print(numbers_power_2)

[1, 4, 9, 16, 25]


In [168]:
# Polymorphism 

class Dog: 
    def eat(self): 
        print("Eating dog food") 

class Cat: 
    def eat(self): 
        print("Eating cat food") 

animal1 = Dog()
animal2 = Cat()

animal1.eat()
animal2.eat()

Eating dog food
Eating cat food


In [169]:
# Operator Overloading 

class Dog: 
    def __init__(self, name, age): 
        self.name = name 
        self.age = age 

    def __gt__(self, other): 
        return True if self.age > other.age  else False 

roger = Dog('Roger', 8) 
syd = Dog('Syd', 9) 

print(roger > syd)

False


In [ ]:
import random

In [195]:
class Card: 
    def __init__(self, suit, rank): 
        self.suit = suit 
        self.rank = rank
    def __str__(self): 
        return self.rank["rank"] + " of " + self.suit

In [217]:
class Deck:
    def __init__(self): 
        self.cards = []
        suits = ["spades", "clubs", "hearts", "diamonds"]
        # suit = suits[2]
        # rank = "K" 
        # value = 10 
        # print("Your card is: " + rank + " of " + suit) 
        # suits.append("snakes") 
        ranks = [{"rank": "A", "value": 11}, 
                 {"rank": "2", "value": 2}, 
                 {"rank": "3", "value": 3}, 
                 {"rank": "4", "value": 4}, 
                 {"rank": "5", "value": 5}, 
                 {"rank" : "6", "value": 6}, 
                 {"rank": "7", "value": 7}, 
                 {"rank": "8", "value": 8}, 
                 {"rank": "9", "vallue": 9}, 
                 {"rank": "10", "value": 10}, 
                 {"rank": "J", "value": 10}, 
                 {"rank": "Q", "value": 10},  
                 {"rank": "K", "value": 10}, ]
        for suit in suits: 
            for rank in ranks: 
                self.cards.append(Card(suit, rank))
    
    def shuffle(self):
        if len(self.cards) > 1: 
            random.shuffle(self.cards)
    
    def deal(self, number): 
        cards_dealt = []
    
        for x in range(number):
            if len(self.cards) > 0:
                card = self.cards.pop() 
                cards_dealt.append(card)
        return cards_dealt

class Hand: 
    def __init__(self, dealer = False): 
        self.cards = []
        self.value = 0
        self.dealer = dealer

    def add_card(self, card_list): 
        self.cards.extend(card_list)

    def calculate_value(self): 
        self.value = 0

        has_ace = False
        for card in self.cards: 
            card_value = int(card.rank["value"]) 
            self.value += card_value
            if card.rank["rank"] == "A": 
                has_ace = True

            if has_ace and self.value > 21: 
                self.value -= 10

    def get_value(self): 
        self.calculate_value()
        return self.value

    def is_blackjack(self): 
        return self.get_value() == 21

    def display(self): 
        print(f'''{"Dealer's" if self.dealer else "Your"} hand:''')

        for index, card in enumerate(self.cards): 
            if index == 0 and self.dealer: 
                print("hidden") 
            else: 
                print(card)

        if not self.dealer: 
            print("Value:", self.get_value()) 

deck = Deck() 
deck.shuffle()

hand = Hand() 
hand.add_card(deck.deal(2))
hand.display()

Your hand:
9 of clubs
8 of diamonds


KeyError: 'value'

In [219]:
import numpy as np
a = np.ones((2, 3))
print(a) 

b = np.full((3, 2), 2)
print(b) 
np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [221]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [222]:
np.min(stats)

1

In [223]:
np.max(stats, axis= 1)

array([3, 6])

In [224]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [227]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

after = before.reshape((8, 1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [230]:
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [231]:
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))

np.hstack([h1, h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])