# Introduction to Python Matrices and Numpy

## 1. Basics of Numpy

In [4]:
import numpy as np 

In [8]:
one_dimensional_arr = np.array([10, 12])

In [10]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [12]:
b = np.arange(3)
print(b)

[0 1 2]


In [13]:
c = np.arange(1, 20, 3)
print(c)

[ 1  4  7 10 13 16 19]


In [15]:
lin_spaced_arr = np.linspace(0, 100, 5)
print(lin_spaced_arr)

[  0.  25.  50.  75. 100.]


In [16]:
ones_arr = np.ones(3)
print(ones_arr)

[1. 1. 1.]


In [18]:
rand_arr = np.random.rand(3)
print(rand_arr)

[0.8652623  0.82453169 0.62900439]


In [21]:
two_dim_arr = np.array([[1, 2, 3], [4, 5,6]])
print(two_dim_arr)

[[1 2 3]
 [4 5 6]]


In [23]:
a = [1, 2, 3, 4, 5]

In [25]:
sliced_arr = a[1:4]
print(sliced_arr)

[2, 3, 4]


In [26]:
sliced_arr = a[:3]
print(sliced_arr)

[1, 2, 3]


In [27]:
sliced_arr = a[::2]
print(sliced_arr)

[1, 3, 5]


In [31]:
a1 = np.array([[1, 1],
             [2, 2]])

a2 = np.array([[3, 3], 
             [4, 4]])

vert_stack = np.vstack((a1, a2))
print(vert_stack)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [33]:
hort_stack = np.hstack((a1, a2))
print(hort_stack)

[[1 1 3 3]
 [2 2 4 4]]


In [37]:
empty_arr = np.empty(3)
print(empty_arr)

[0.8652623  0.82453169 0.62900439]


In [42]:
A = np.array([
        [-1, 3], 
        [3, 2]])
b = np.array([7, 1])

In [43]:
A_system = np.hstack((A, b.reshape(2, 1)))
print(A_system)

[[-1  3  7]
 [ 3  2  1]]


In [46]:
d2 = np.linalg.det(A)
print(d2)

-11.000000000000002


In [48]:
x = np.linalg.solve(A, b)
print(x)

[-1.  2.]


In [49]:
A = np.array([
    [4, -3, 1], 
    [2, 1, 3], 
    [-1, 2, -5], 
], dtype = np.dtype(float))

b = np.array([-10, 0, 17], dtype = np.dtype(float))

In [50]:
x = np.linalg.solve(A, b)
print(x)

[ 1.  4. -2.]


In [52]:
A = np.array([
    [4, 9, 9], 
    [9, 1, 6], 
    [9, 2, 3], 
])

B = np.array([
    [2, 2], 
    [5, 7], 
    [4, 4]
])

In [53]:
np.matmul(A, B)

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

In [54]:
A@B

array([[ 89, 107],
       [ 47,  49],
       [ 40,  44]])

In [55]:
A_eig = np.linalg.eig(A) 
print(A_eig)

EigResult(eigenvalues=array([17.68520368, -7.51953905, -2.16566463]), eigenvectors=array([[-0.68056154, -0.73600638, -0.31968239],
       [-0.54370841,  0.38568745, -0.55148916],
       [-0.49113862,  0.55636302,  0.77049521]]))
